#!/bin/sh
# Download and install binary updates from remote a server

# Set up directories
arch="$(cat ${KISS_ROOT}/etc/os-arch)"
cac_dir="${XDG_CACHE_HOME:-${HOME:?HOME is null}/.cache}/kiss"
bin_repo="${KISS_BINREPO:-$arch}"
bin_dir="$cac_dir/bin/$bin_repo"
bup_dir="$cac_dir/bup"
remote_dir=$KISS_REMOTE_REPO
repo_index_name=repo.index

if [ -z "$remote_dir" ]; then
    echo "You must set KISS_REMOTE_REPO"
    exit 1
fi

echo "Getting hashes for from $remote_dir"

# Prepare files if they don't exist
mkdir -p $bup_dir
mkdir -p $bin_dir
touch $bin_dir/$repo_index_name

# Get list of hashes from the remote server
curl -s "$remote_dir/$repo_index_name" > $bup_dir/$repo_index_name

# For each remote hash, see if it's different to the local repo
# Download and install the package if it's different
cd $bup_dir
cat $repo_index_name | while read -r key val; do
    different=`grep "$val" $bin_dir/$repo_index_name | grep "$key"`

    if [ -z "$different" ]; then
        echo "$val"
        curl -# -o "$bup_dir/$val" "$remote_dir/$val"
        KISS_FORCE=1 kiss i $val

        # Update the repo index with the new package hash
        sed -i "/${val%@*}@/d" $bin_dir/$repo_index_name
        sha256sum $val >> $bin_dir/$repo_index_name
        mv $val $bin_dir
    fi

done
