#!/bin/sh -e
# List orphaned packages

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    case $pkg in
        # Exemptions for orphans which aren't really
        # orphans. Exclude them from the list.
        baseinit|baselayout|llvm|e2fsprogs|musl|\
        make|cmake|busybox|bzip2|grub|kiss|git|\
        linux-headers|python|byacc|flex)
            continue
    esac

    grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
done
