#!/bin/sh -e
# List orphaned packages

cd "$KISS_ROOT/var/db/kiss/installed/"

for pkg in *; do
    case $pkg in
        # Exemptions for orphans which aren't really
        # orphans. Exclude them from the list.
        baselayout|busybox|bzip2|curl|\
        git|gzip|kiss|libressl|llvm|\
        make|musl|xz|zlib)

            continue
    esac

    grep -q "^$pkg$" ./*/depends || printf '%s\n' "$pkg"
done
